version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers:
      - "snapsnapturtle"
    groups:
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "typescript-eslint"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "snapsnapturtle"
